// Code generated by Slice Machine. DO NOT EDIT.

import Publication from "./Publication/index.svelte";
import Project from "./Project/index.svelte";

export const components = {
  book: Publication,
  project: Project,
};
