// Code generated by Slice Machine. DO NOT EDIT.

import Book from "./Book/index.svelte";
import Project from "./Project/index.svelte";

export const components = {
  book: Book,
  project: Project,
};
